### ISSUE TITLE
Production ready 

### ISSUE THREAD

**Issue by ddennis** [maximilianschmitt/gulp-ng-autobootstrap#2]
Hi 
This seems like a very cool idea, have you implemented this in production? and bigger projects?
/Dennis

**Comment by maximilianschmitt** [comment]
Thanks Dennis! I'm using it to develop https://thoughtplan.com for example and it makes my life a lot easier. If you're starting a new project, you can try it out and easily move away from it if you don't like it. And let me know if you need any assistance, I'm happy to help out! :)

**Comment by ddennis** [comment]
Super, i will dig in and start using it.

Your Youtube tutorials have been of great help, especially the gulp series helped me switch from Grunt, thanks alot. 

/Dennis
