### ISSUE TITLE
animations directiv

### ISSUE THREAD

**Issue by ddennis** [maximilianschmitt/gulp-ng-autobootstrap#3]
When i make a animation directory and called "animations" and put in the following directive, like so:

    var slideAnimation = function () {
    		return {
			beforeAddClass: function (element, className, done) {			
				...
			},
			removeClass: function (element, className, done) {
				...
			}
		};
    }
    module.exports = slideAnimation

My directiv does not work. This is how it appears in the bootstrap.js

    app.animation('slide-animation', require('./animations/slideAnimation'));

However if i paste the same animation directive in to my main app file like this:

    var app = angular.module('fanApp',[
		'ngAnimate',
		'ui.router'
	], function config($httpProvider) {
		$httpProvider.interceptors.push('AuthInterceptor');
	})
	.animation('.slide-animation', function () {
			return {
				beforeAddClass: function (element, className, done
				},

				removeClass: function (element, className, done) {			
				}
			};
		});

Then it works fine, I am still just learning angular, but i assume the ".slide-animation" dot is required, but i can figure out how to add it. 

The directive is used like this in the mark up:

    class="slide-animation"

Otherwise thanks for a great tool.

/Dennis

**Comment by maximilianschmitt** [comment]
Thanks for opening an issue, @ddennis. It looks like you're right about the required `.`. Feel free to open a pull request to [ng-autobootstrap](https://github.com/maximilianschmitt/ng-autobootstrap) and I'll merge the fix. If you're not sure how, I'll take a look these coming days.

Anyway, thanks for the kind words and contributing!

**Comment by ddennis** [comment]
Hi I wish i could provide you with a pull request, i am still a litlle lost in the nodemodules. 

I am crossing my fingers and hope you will find the time to update it.

Thanks in advance.
/Dennis

**Comment by maximilianschmitt** [comment]
@ddennis, I just updated ng-autobootstrap to fix the animation imports. You will need to reinstall by doing `rm -rf node_modules && npm install` so that you get the latest version. I hope this fixes the issue for you, let me know if not!

**Comment by ddennis** [comment]
Thanks alot for a speedy fix.
I will update asap.
/Dennis
